### ISSUE TITLE
Allow Composable Component

### ISSUE THREAD

**Issue by simeonoff** [IgniteUI/igniteui-webcomponents#228]
## Description

So far all themes, except the material one, which is the one all components encapsulate, are included via a global theme. This works well for simple components but we face an issue when more complex components use other components as part of their template. In those instances, the global themes cannot penetrate the shadow DOM and thus, internal components remain with the default material theme.

## Proposal

Components should dynamically switch the encapsulated styles based on some global configuration. This could happen via a `theme` property on each component or in another more generic way.

## TODO(s):

- [ ] Implement a mechanism to allow for dynamic theme switching on the component level.

Refactor affected component themes so all variants use the shadow DOM selectors for styling. Those components are:
- [x] Badge - @didimmova 
- [x] Button - @didimmova 
- [x] Calendar - @desig9stein 
- [x] Card - @SisIvanova 
- [x] Checkbox - @SisIvanova  
- [x] Icon Button - @didimmova 
- [x] Input - @simeonoff 
- [x] List - @didimmova 
- [x] Navbar - @SisIvanova 
- [x] Nav Drawer - @desig9stein 
- [x] Radio Button - @didimmova
- [x] (Range) Slider - @SisIvanova 
- [x] Switch - @SisIvanova
